---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: scoreserver
  name: scoreserver

---
apiVersion: v1
kind: Service
metadata:
  name: scoreserver-service
spec:
  selector:
    app: scoreserver
  ports:
    - port: 80 
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: scoreserver
  name: scoreserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scoreserver
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: scoreserver
    spec:
      containers:
        - image: scoresvr
          name: scoresvr
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: "/app/scores"
              name: scores-mount
      volumes:
        - name: scores-mount
          hostPath:
            path: "/scores"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scoreserver-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /scoreserver
        backend:
          service:
            name: scoreserver-service
            port:
              number: 80
