apiVersion: v1
kind: Service
metadata:
  name: scoreserver-service
spec:
  selector:
    app: scoreserver
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: scoreserver
  name: scoreserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scoreserver
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: scoreserver
    spec:
      containers:
        - image: scoresvr
          name: scoresvr
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: "/app/scores"
              name: scores-mount
        - image: scoresvr-httpd
          name: scoresvr-httpd
          imagePullPolicy: IfNotPresent
      volumes:
        - name: scores-mount
          hostPath:
            path: "/scores"
