version: '3'

env:
  CLUSTER_NAME: iron-1
  NAMESPACE: scoreserver
  REGISTRY: localhost:5001
  APP_IMAGE: scoresvr

tasks:
  ### Standalone tasks
  init:
    cmds:
      - kubectl create namespace $NAMESPACE
      - kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
      - |
        kubectl patch deployment ingress-nginx-controller -n ingress-nginx --type='json' -p='[
          {"op": "add", "path": "/spec/template/spec/nodeSelector", "value": {"kubernetes.io/hostname": "'$CLUSTER_NAME'-control-plane"}}
        ]'
      - kubectl wait -n ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=90s
      - kubectl apply -f manifests/scoresvr-nginx-configmap.yaml -n $NAMESPACE
      - kubectl apply -f manifests/scoreserver.yaml -n $NAMESPACE
      - kubectl apply -f manifests/service.yaml -n $NAMESPACE
      - kubectl apply -f manifests/ingress.yaml -n $NAMESPACE

  destroy:
    cmds:
      - kubectl delete -f manifests/ingress.yaml -n $NAMESPACE
      - kubectl delete -f manifests/service.yaml -n $NAMESPACE
      - kubectl delete -f manifests/scoreserver.yaml -n $NAMESPACE
      - kubectl delete -f manifests/scoresvr-nginx-configmap.yaml -n $NAMESPACE
      - kind delete cluster --name $CLUSTER_NAME

  clean:
    cmds:
      - rm .build_id
      - rm .stopped
  ###

  build:
    cmds:
      - docker build . -t $REGISTRY/$APP_IMAGE
      - cmd: echo $(date +%F_%H%M%S) > .build_id
        silent: true
    sources:
      - Dockerfile
      - src/app/main.py

  push:
    deps:
      - build
    cmds:
      - docker push $REGISTRY/$APP_IMAGE
    sources:
      - .build_id

  stop:
    cmds:
      - kubectl delete -f manifests/scoreserver.yaml -n $NAMESPACE
      - cmd: touch .stopped
        silent: true
    status:
      - test -f .stopped
    ignore_error: true

  deploy:
    deps:
      - stop
      - push
    cmds:
      - kubectl apply -f manifests/scoreserver.yaml -n $NAMESPACE
      - cmd: rm .stopped
        silent: true
    sources:
      - .build_id
