---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scoreserver-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /scoreserver
        backend:
          service:
            name: scoreserver-service
            port:
              number: 80
