---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: scoreserver
  name: scoreserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scoreserver
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: scoreserver
    spec:
      containers:
        - image: scoresvr
          name: scoresvr
          imagePullPolicy: Never
        - image: scoresvr-nginx
          name: scoresvr-nginx
          imagePullPolicy: Never
        - image: mongodb/mongodb-community-server
          name: scoredb
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: "/data/db"
              name: scores-data
      volumes:
        - name: scores-data
          hostPath:
            path: "/data"

